image: borjatur/custom-gitlab-ci:latest
services:
- docker:dind

stages:
- build
- lint-test
- release
- deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  CONTAINER_NAME: node-sample
  CONTAINER_TEST_IMAGE: $DOCKER_REGISTRY/$CONTAINER_NAME:$CI_BUILD_REF
  CONTAINER_RELEASE_IMAGE: $DOCKER_REGISTRY/$CONTAINER_NAME:latest

before_script:
  - make ci-before-script

build:
  stage: build
  script:
    - make ci-container-build-image

lint-test:
  stage: lint-test
  script:
     - make ci-lint-test

release-image:
  stage: release
  only:
    - master
  script:
    - make ci-release-image

deploy-app:
  stage: deploy
  only:
    - master
  script:
    - make ci-deploy


