image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release
- deploy

variables:
  CONTAINER_NAME: node-sample
  CONTAINER_TEST_IMAGE: $DOCKER_REGISTRY/$CONTAINER_NAME:$CI_BUILD_REF
  CONTAINER_RELEASE_IMAGE: $DOCKER_REGISTRY/$CONTAINER_NAME:latest
  AWS_DEFAULT_REGION: eu-central-1

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

unit-test:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE npm test

release-image:
  stage: release
  only:
    - master
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE

deploy-app:
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.13.7/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - echo $K8S_CONFIG | base64 -d > gitlab-config
    - kubectl --kubeconfig=gitlab-config version
    - sed -i "s/<DOCKER_REGISTRY>/${DOCKER_REGISTRY}/g" deployment.yml
    - sed -i "s/<VERSION>/${CI_BUILD_REF}/g" deployment.yml
    - sed -i "s/<SERVICE_HOST>/${SERVICE_HOST}/g" deployment.yml
    - kubectl --kubeconfig=gitlab-config apply -f deployment.yml


