apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node-sample
          image: <DOCKER_REGISTRY>/node-sample:<VERSION>
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 2
---

kind: Service
apiVersion: v1
metadata:
  name: test-server-service
spec:
  selector:
    app: node
  ports:
    - port: 3000 # Default port for image