apiVersion: apps/v1
kind: Deployment
metadata:
  name: $POS_APP_NAME
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: $POS_APP_NAME
          image: $DOCKER_REGISTRY/$POS_APP_NAME@$DOCKER_RELEASE_SHA
          imagePullPolicy: Always
          ports:
            - containerPort: $POS_APP_PORT
          livenessProbe:
            httpGet:
              path: /healthz
              port: $POS_APP_PORT
            initialDelaySeconds: 2
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: $POS_APP_PORT
            initialDelaySeconds: 2
            periodSeconds: 2
---
kind: Service
apiVersion: v1
metadata:
  name: $POS_APP_NAME-service
spec:
  selector:
    app: node
  ports:
    - port: $POS_APP_PORT # Default port for image
---    
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: test-ingress
spec:
  rules:
    - host: $SERVICE_HOST
      http:
        paths:
        - path: /
          backend:
            serviceName: $POS_APP_NAME-service
            servicePort: $POS_APP_PORT